name: Run API Tests

on:
  workflow_run:
    workflows: ["Build All Projects"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      MCSA_TEST_USER: ${{ secrets.MCSA_TEST_USER }}
      MCSA_TEST_PASSWORD: ${{ secrets.MCSA_TEST_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Tests
        run: dotnet restore api/MCSA_API.Tests/MCSA_API.Tests.csproj

      - name: Run tests
        run: dotnet test api/MCSA_API.Tests/MCSA_API.Tests.csproj --no-restore --configuration Release --verbosity normal