name: Build All Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        solution:
          - api/MCSA-API.sln
          - desktop/MissingChildrenSA.sln
          - mobile/MissingChildrenSA.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove pre-installed .NET 9 SDKs except 9.0.106
        run: |
            $ErrorActionPreference = "Continue"
            $installedSdks = Get-ChildItem "C:\Program Files\dotnet\sdk" | Where-Object { $_.Name -like "9.0.*" -and $_.Name -ne "9.0.106" }
            foreach ($sdk in $installedSdks) {
                $fullPath = $sdk.FullName
                Write-Host "Removing SDK: $fullPath"
                Remove-Item -Recurse -Force $fullPath
            }

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.106
      - name: Restore
        run: dotnet restore ${{ matrix.solution }}

      - name: Build
        run: dotnet build ${{ matrix.solution }} --no-restore --configuration Release