name: Build All Projects

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        solution:
          - api/MCSA-API.sln
          - desktop/MissingChildrenSA.sln
          - mobile/MissingChildrenSA.sln

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Restore
        run: |
          if [[ "${{ matrix.solution }}" == *"mobile/"* ]]; then
            dotnet restore ${{ matrix.solution }} --runtime android-arm64 --runtime ios-arm64 --runtime maccatalyst-arm64 --runtime win-x64
          else
            dotnet restore ${{ matrix.solution }}
          fi
        shell: bash

      - name: Build
        run: dotnet build ${{ matrix.solution }} --no-restore --configuration Release